// examples/vue-query/src/App.vue
<script lang="ts">
import { defineComponent, ref } from 'vue'
import type { FindPetsByStatusQueryParamsStatus } from './gen/models/FindPetsByStatus.ts'
import Pets from './Pets.vue'

export default defineComponent({
  name: 'App',
  components: { Pets },
  setup() {
    const status = ref<FindPetsByStatusQueryParamsStatus>('available')

    return {
      status,
      setStatus(newStatus: FindPetsByStatusQueryParamsStatus) {
        status.value = newStatus
      },
    }
  },
})
</script>

<template>
  <Pets :status="status" @setStatus="setStatus" />
</template>

// examples/react-query-v5/src/App.tsx
import { useState } from 'react'
import type { FindPetsByStatusQueryParamsStatus } from './gen'
import { useFindPetsByStatusHook } from './gen'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'

const queryClient = new QueryClient()

function Pets(): JSX.Element {
  const [status, setStatus] = useState<FindPetsByStatusQueryParamsStatus>('available')
  const { data: pets } = useFindPetsByStatusHook({ status })

  return (
    <>
      <h1>Pets: {status}</h1>
      <ul>{pets?.map((pet) => <li key={pet.id}>{pet.name}</li>)}</ul>
      <button onClick={() => setStatus('available')}>Available</button>
      <button onClick={() => setStatus('pending')}>Pending</button>
    </>
  )
}

export function App(): JSX.Element {
  return (
    <QueryClientProvider client={queryClient}>
      <Pets />
      <ReactQueryDevtools initialIsOpen={false} />
    </QueryClientProvider>
  )
}
